### PR TITLE
Index, css and img added

### PR DESCRIPTION
**Pull request by suretrust**
Submitting for code review.

### CODE REVIEW

**Review by zlayabekrija — CHANGES_REQUESTED** [review]
Great work for your first project guys. 
There are some things to be changed

Please use this link https://htmlpreview.github.io/?https://raw.githubusercontent.com/suretrust/html-video-embed/development/index.html for the preview of your project. Over there you'll find that stylesheet was not properly loaded. The path is most probably the reason

The logo should be proportional close to the original site
Navbar should include the search field
Navbar should include some icons, font awesome will do the job
Some margin between navbar and main content

The main video should have name and number of views and should be centered (optionally you can add icons for like and share, use fontawesome)
Underneath the main video should be a short description and subscribe button
Lastly on the main video side, put some fake comments, would be great.

Aside was done really good yet few changes I would ask you for:

Video thumbnail should be on the left side, while title, author, and comments should be on the right.
Some margin would look good. For anchor please place the div outside of it, and there should be an anchor for video and for the title and author separably.

If you are using floats, please don't forget to clear the float.
There is no need for a footer.

Please make requested changes and submit the new review request.

**Comment by suretrust** [comment]
Changes made as advised. Re-submitting for review @zlayabekrija

**Review by zlayabekrija — CHANGES_REQUESTED** [review]
Excellent work, but again there are some things to update.
Line 79 of CSS file has padding of 56%, any margin and padding shouldn't be bigger than 15 px, or else there must be another solution.
Line 85 of CSS do you really need position absolute in this case? Adjust it, please.
In HTML please correct aside links, video thumbnail, title, author and view count should be separate links.
Please make adjustments if you are having issues contact me on Slack on @zlaja.bekrija.
After corrections are made you'll have my thumbs up.

Happy coding.

**Comment by suretrust** [comment]
We tried using:

`position: relative;
overflow: hidden;
text-align: center;` for video div and:

`width: 720px;
height: 480px;
border: 0;` for iframe but it did not work. 

We further searched the internet for other possible solutions but this current solution was all we found all over the internet if we are really going to make the iframe responsive. 

Thanks.

**Review by zlayabekrija — APPROVED** [review]
Review the message on slack, please.
You got thumbs up 👍

**Pull request merged**
